# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-16 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStudySecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u7c7b\u578b')),
                ('questionNumber', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u5e8f\u53f7')),
                ('questionContent', models.CharField(max_length=100, verbose_name='\u95ee\u9898\u5185\u5bb9')),
                ('AnswerA', models.CharField(max_length=50, verbose_name='\u7b54\u6848A')),
                ('AnswerB', models.CharField(max_length=50, verbose_name='\u7b54\u6848B')),
                ('AnswerC', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848C')),
                ('AnswerD', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848D')),
                ('AnswerE', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848E')),
                ('AnswerF', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848F')),
                ('AnswerG', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848G')),
                ('AnswerH', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848H')),
                ('questionScore', models.CharField(default='2', max_length=5, verbose_name='\u5206\u503c')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5b66\u4e60\u6d3b\u52a8\u5b89\u5168\u95ee\u9898',
                'verbose_name_plural': '\u5b66\u4e60\u6d3b\u52a8\u5b89\u5168\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='FireSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u7c7b\u578b')),
                ('questionNumber', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u5e8f\u53f7')),
                ('questionContent', models.CharField(max_length=100, verbose_name='\u95ee\u9898\u5185\u5bb9')),
                ('AnswerA', models.CharField(max_length=50, verbose_name='\u7b54\u6848A')),
                ('AnswerB', models.CharField(max_length=50, verbose_name='\u7b54\u6848B')),
                ('AnswerC', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848C')),
                ('AnswerD', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848D')),
                ('AnswerE', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848E')),
                ('AnswerF', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848F')),
                ('AnswerG', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848G')),
                ('AnswerH', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848H')),
                ('questionScore', models.CharField(default='2', max_length=5, verbose_name='\u5206\u503c')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6d88\u9632\u5b89\u5168\u95ee\u9898',
                'verbose_name_plural': '\u6d88\u9632\u5b89\u5168\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='FoodSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u7c7b\u578b')),
                ('questionNumber', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u5e8f\u53f7')),
                ('questionContent', models.CharField(max_length=100, verbose_name='\u95ee\u9898\u5185\u5bb9')),
                ('AnswerA', models.CharField(max_length=50, verbose_name='\u7b54\u6848A')),
                ('AnswerB', models.CharField(max_length=50, verbose_name='\u7b54\u6848B')),
                ('AnswerC', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848C')),
                ('AnswerD', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848D')),
                ('AnswerE', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848E')),
                ('AnswerF', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848F')),
                ('AnswerG', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848G')),
                ('AnswerH', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848H')),
                ('questionScore', models.CharField(default='2', max_length=5, verbose_name='\u5206\u503c')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u98df\u54c1\u5b89\u5168\u95ee\u9898',
                'verbose_name_plural': '\u98df\u54c1\u5b89\u5168\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='LegalSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u7c7b\u578b')),
                ('questionNumber', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u5e8f\u53f7')),
                ('questionContent', models.CharField(max_length=100, verbose_name='\u95ee\u9898\u5185\u5bb9')),
                ('AnswerA', models.CharField(max_length=50, verbose_name='\u7b54\u6848A')),
                ('AnswerB', models.CharField(max_length=50, verbose_name='\u7b54\u6848B')),
                ('AnswerC', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848C')),
                ('AnswerD', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848D')),
                ('AnswerE', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848E')),
                ('AnswerF', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848F')),
                ('AnswerG', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848G')),
                ('AnswerH', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848H')),
                ('questionScore', models.CharField(default='2', max_length=5, verbose_name='\u5206\u503c')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6cd5\u5236\u5b89\u5168\u95ee\u9898',
                'verbose_name_plural': '\u6cd5\u5236\u5b89\u5168\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='MentalHealthSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u7c7b\u578b')),
                ('questionNumber', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u5e8f\u53f7')),
                ('questionContent', models.CharField(max_length=100, verbose_name='\u95ee\u9898\u5185\u5bb9')),
                ('AnswerA', models.CharField(max_length=50, verbose_name='\u7b54\u6848A')),
                ('AnswerB', models.CharField(max_length=50, verbose_name='\u7b54\u6848B')),
                ('AnswerC', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848C')),
                ('AnswerD', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848D')),
                ('AnswerE', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848E')),
                ('AnswerF', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848F')),
                ('AnswerG', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848G')),
                ('AnswerH', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848H')),
                ('questionScore', models.CharField(default='2', max_length=5, verbose_name='\u5206\u503c')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5fc3\u7406\u5065\u5eb7\u5b89\u5168\u95ee\u9898',
                'verbose_name_plural': '\u5fc3\u7406\u5065\u5eb7\u5b89\u5168\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='NationalSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u7c7b\u578b')),
                ('questionNumber', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u5e8f\u53f7')),
                ('questionContent', models.CharField(max_length=100, verbose_name='\u95ee\u9898\u5185\u5bb9')),
                ('AnswerA', models.CharField(max_length=50, verbose_name='\u7b54\u6848A')),
                ('AnswerB', models.CharField(max_length=50, verbose_name='\u7b54\u6848B')),
                ('AnswerC', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848C')),
                ('AnswerD', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848D')),
                ('AnswerE', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848E')),
                ('AnswerF', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848F')),
                ('AnswerG', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848G')),
                ('AnswerH', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848H')),
                ('questionScore', models.CharField(default='2', max_length=5, verbose_name='\u5206\u503c')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u56fd\u5bb6\u5b89\u5168\u95ee\u9898',
                'verbose_name_plural': '\u56fd\u5bb6\u5b89\u5168\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='NetworkSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u7c7b\u578b')),
                ('questionNumber', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u5e8f\u53f7')),
                ('questionContent', models.CharField(max_length=100, verbose_name='\u95ee\u9898\u5185\u5bb9')),
                ('AnswerA', models.CharField(max_length=50, verbose_name='\u7b54\u6848A')),
                ('AnswerB', models.CharField(max_length=50, verbose_name='\u7b54\u6848B')),
                ('AnswerC', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848C')),
                ('AnswerD', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848D')),
                ('AnswerE', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848E')),
                ('AnswerF', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848F')),
                ('AnswerG', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848G')),
                ('AnswerH', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848H')),
                ('questionScore', models.CharField(default='2', max_length=5, verbose_name='\u5206\u503c')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7f51\u7edc\u5b89\u5168\u95ee\u9898',
                'verbose_name_plural': '\u7f51\u7edc\u5b89\u5168\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='PersonalSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u7c7b\u578b')),
                ('questionNumber', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u5e8f\u53f7')),
                ('questionContent', models.CharField(max_length=100, verbose_name='\u95ee\u9898\u5185\u5bb9')),
                ('AnswerA', models.CharField(max_length=50, verbose_name='\u7b54\u6848A')),
                ('AnswerB', models.CharField(max_length=50, verbose_name='\u7b54\u6848B')),
                ('AnswerC', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848C')),
                ('AnswerD', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848D')),
                ('AnswerE', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848E')),
                ('AnswerF', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848F')),
                ('AnswerG', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848G')),
                ('AnswerH', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848H')),
                ('questionScore', models.CharField(default='2', max_length=5, verbose_name='\u5206\u503c')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4eba\u8eab\u8d22\u4ea7\u5b89\u5168\u95ee\u9898',
                'verbose_name_plural': '\u4eba\u8eab\u8d22\u4ea7\u5b89\u5168\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='TrafficSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u7c7b\u578b')),
                ('questionNumber', models.CharField(max_length=10, verbose_name='\u95ee\u9898\u5e8f\u53f7')),
                ('questionContent', models.CharField(max_length=100, verbose_name='\u95ee\u9898\u5185\u5bb9')),
                ('AnswerA', models.CharField(max_length=50, verbose_name='\u7b54\u6848A')),
                ('AnswerB', models.CharField(max_length=50, verbose_name='\u7b54\u6848B')),
                ('AnswerC', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848C')),
                ('AnswerD', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848D')),
                ('AnswerE', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848E')),
                ('AnswerF', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848F')),
                ('AnswerG', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848G')),
                ('AnswerH', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7b54\u6848H')),
                ('questionScore', models.CharField(default='2', max_length=5, verbose_name='\u5206\u503c')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4ea4\u901a\u5b89\u5168\u95ee\u9898',
                'verbose_name_plural': '\u4ea4\u901a\u5b89\u5168\u95ee\u9898',
            },
        ),
    ]
