# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystudysecurity',
            name='RightAnswer',
            field=models.CharField(default='A', max_length=50, verbose_name='\u6b63\u786e\u7b54\u6848'),
        ),
        migrations.AddField(
            model_name='firesecurity',
            name='RightAnswer',
            field=models.CharField(default='A', max_length=50, verbose_name='\u6b63\u786e\u7b54\u6848'),
        ),
        migrations.AddField(
            model_name='foodsecurity',
            name='RightAnswer',
            field=models.CharField(default='A', max_length=50, verbose_name='\u6b63\u786e\u7b54\u6848'),
        ),
        migrations.AddField(
            model_name='legalsecurity',
            name='RightAnswer',
            field=models.CharField(default='A', max_length=50, verbose_name='\u6b63\u786e\u7b54\u6848'),
        ),
        migrations.AddField(
            model_name='mentalhealthsecurity',
            name='RightAnswer',
            field=models.CharField(default='A', max_length=50, verbose_name='\u6b63\u786e\u7b54\u6848'),
        ),
        migrations.AddField(
            model_name='nationalsecurity',
            name='RightAnswer',
            field=models.CharField(default='A', max_length=50, verbose_name='\u6b63\u786e\u7b54\u6848'),
        ),
        migrations.AddField(
            model_name='networksecurity',
            name='RightAnswer',
            field=models.CharField(default='A', max_length=50, verbose_name='\u6b63\u786e\u7b54\u6848'),
        ),
        migrations.AddField(
            model_name='personalsecurity',
            name='RightAnswer',
            field=models.CharField(default='A', max_length=50, verbose_name='\u6b63\u786e\u7b54\u6848'),
        ),
        migrations.AddField(
            model_name='trafficsecurity',
            name='RightAnswer',
            field=models.CharField(default='A', max_length=50, verbose_name='\u6b63\u786e\u7b54\u6848'),
        ),
    ]
